FLAGS=-Wall -Wextra -Werror -rdynamic
SOURCES=../src/logging.c ../src/hash.c ../src/others.c ../src/secure_stack.c
MAIN=example.c
EXECUTABLE=stack_example.out

all:
	gcc $(FLAGS) $(SOURCES) $(MAIN) -o $(EXECUTABLE)
